### ISSUE TITLE
item duping with "Item Frame" wall mounted item

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1039]
If you place an item frame on a wall somewhere, then just spam right click it dupes the item you have framed.

similar to the weapon rack issue

**Comment by Patrikkk** [comment]
I tested this with TShock 4.3.7.
Game says as if I got duplicate items, the number is increasing, (http://puu.sh/jbnvt/324187e4ec.jpg)
but I only have that one item. So no duplicate. 
I also got an other person test this. They didn't get any duplicates either. (only the message as in my screenshot)

**Comment by tysonstrange** [comment]
If you have access to the area it works differently.

If there is an item frame in a protected region and a player without permission to the region tries to remove the item or add and remove an item it will duplicate.

I tested it in the new tshock as well and it seemsi to be ok with a few items too

**Comment by Marcus101RR** [comment]
So If it is not in a protected/unprotected region it works fine? I got to test that out.

**Comment by hastinbe** [comment]
I've come up with a couple different solutions. This one I wrote into TerrariaServer's cheat protection. It's important to note that TShock disables this in TerrariaServer so I've modified TShock too. Maybe someone can explain why it's disabled.

Here it is in action: ![Terraria ItemFrame cheat detection](https://s3.amazonaws.com/f.cl.ly/items/1e421t1t1M0T3s2f3I2O/out3.gif)

**Comment by Ijwu** [comment]
@hastinbe I would rather have the fix be in TShock which seems to be causing this issue solely based on the fact that it has to due with protected region and item frame interaction. My guess is simply that it's letting the client have the item while resetting the item frame due to the fact that the client does not have permission to actually edit the item frame.

Using this assumption, possible solutions that I am in favor of include:
* If the item is spawned server-side: stop the packet before it goes out.
* If the item is spawned client-side: destroy the item before the client gets it.
* If SSC is enabled: edit inventory to ensure no duplicates are kept.
* Kick if client continuously right clicks item frame in protected region (from TShock, not from TSAPI)

I would rather not have to enable `TerrariaServer.exe`'s built in cheat-protection because it's been disabled for the lifetime of TShock and I have no idea how it would interact with our current protections. Not to mention that it may be an overlap in cheat protection and the tolerance in the EXE may be lower or not configurable as it is in TShock.

**Comment by WhiteXZ** [comment]
The item frame duping issue is likely much the same as the weapon rack duping issue which was fixed by black magic and messing with frames

**Comment by WhiteXZ** [comment]
Moved to https://github.com/NyxStudios/TShock/issues/1160
