### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by nohatssir** [NyxStudios/TShock#1092]
At the moment managing the server on a headless Linux server is a bit more difficult than it should be. It involves using other services such as screen or tmux to be able to shutdown the server and save the map before doing so.

To circumvent the lack of a graceful shutdown option and to make it a bit easier to manage the server I thought I could just write a simple Python script to wrap the server. The script traps SIGTERM/SIGINT and then sends the exit command to the server through stdin. But then I noticed this only works with the vanilla server since the following commit https://github.com/NyxStudios/TerrariaAPI-Server/commit/08f43e365adc25733a6d49d4044878004aba4fef makes it impossible to send data to the server when you redirect stdin. So at the moment there's is no way besides using screen and tmux (which IMHO is not a good solution) to handle a graceful shutdown.

Is there any way we could have it so that the server listens for SIGTERM (and possibly SIGINT) and then performs a graceful shutdown of the server by saving the map before exiting?

**Comment by tylerjwatson** [comment]
Hi,

Firstly, mono has no scope to handle signals since signaling doesn't work on windows, and .NET code should always run regardless of platforms.  This is annoying and is why mono doesn't support `fork()` and other POSIX-based things that would make it a WBUD, thus controlling it would require us to put in some mono-specific code which will break TSAPI under windows.

It is true that it used to listen for commands through stdin, however that requires yet another dead thread running inside the process that's ultimately going to be blocked for the entire lifetime of the application; it doesn't make sense to listen for input when the process doesn't have a pty.  So, I removed it.

With all that said, controlling it will have to happen through an IPC mechanism (which most linux programs already do, just through socket fd's) and TShock does support this through it's [REST interface](https://tshock.atlassian.net/wiki/display/TSHOCKPLUGINS/REST+API+Endpoints#RESTAPIEndpoints-/v2/server/off) which has the ability to cause the server to shutdown.

Manipulating this API would be dead simple to do with a shell script and `curl` to signal the server to shutdown, I'd probably go down this path, especially with a systemd-based distro that could use `ExecStop` et al. unit directives.

To directly answer your question: Respectifully, no there is no way we could have it so the server listens for signals, as signals are a POSIX-only paradigm and aren't cross-compatible.

Cheers!

**Comment by GGG-KILLER** [comment]
I believe this could now be implemented using [AppDomain.CurrentDomain.ProcessExit](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=net-6.0) after the .NET 6.0 migration since this API exists since .NET Core 2.0.

This works in "normal" (or bare, not sure how to call it) Linux as well as inside Docker.
In .NET Framework it used to have a 2 second timeout however there's no such thing in .NET so it could be used to kick players, save world and other shutdown operations.

**Comment by sgkoishi** [comment]
> I believe this could now be implemented using [AppDomain.CurrentDomain.ProcessExit](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=net-6.0) after the .NET 6.0 migration since this API exists since .NET Core 2.0.
> 
> This works in "normal" (or bare, not sure how to call it) Linux as well as inside Docker. In .NET Framework it used to have a 2 second timeout however there's no such thing in .NET so it could be used to kick players, save world and other shutdown operations.

https://github.com/Pryaxis/TShock/blob/2c06e2bdf5d3057aaaaf7588519ce9ee305d7079/TShockAPI/TShock.cs#L756-L775

I think it's already done for a while, like say, two years ago https://github.com/Pryaxis/TShock/commit/34da464bab734f81a7a7209ab5029767c73e800d?

**Comment by GGG-KILLER** [comment]
Oh I see, I recently tried to send a SIGTERM to a docker container and it didn't react so I assumed this hadn't been done, my bad!

Might need to investigate why it is not working in my case then, thanks for the reply!

**Comment by GGG-KILLER** [comment]
Actually, that is a different implementation, that looks at the CTRL+C keypress, it doesn't react to SIGTERM or any other program close requests.

I believe a similar handler could be used with [AppDomain.CurrentDomain.ProcessExit](https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?view=net-6.0) to enable graceful shutdown in non-interactive scenarios such as docker containers or systemd services.

**Comment by sgkoishi** [comment]
Kind of - it handles [`SIGINT` and `SIGQUIT` but not `SIGTERM` or `SIGKILL`](https://source.dot.net/#System.Console/System/Console.cs,5ab6c3abde6b46c4,references)
