### ISSUE TITLE
SSC Shared between servers,

### ISSUE THREAD

**Issue by ChetwyndKid** [NyxStudios/TShock#1103]
Ive been doing a look around TShock and sorry if i missed it but can not see a way to share a SSC between servers, Or change the location of where the SSC is saved. Because even if i could change the save location i can make 2 servers share the same SSC for a farmworld and a Buildworld.

**Comment by TeeriaLLC** [comment]
There are two options, you could possibly make an mlink (I suppose it is called an mlink) between the same sqlite database but the downside of using sqlite is that it is not live and could cause issues. The second option is to move to MySQL (If not already using mysql) and let two servers use the same database. You might get some issues regarding chest data and players being able to be online on the two worlds at once and duplicating items.

**Comment by ChetwyndKid** [comment]
Is there no way to change the folder of where they save?

**Comment by TeeriaLLC** [comment]
I do not think so unless you edit the source.

**Comment by flyingmoose** [comment]
I guess you could symbolic link the folder to a shared folder? Kinda hackish though.

**Comment by tylerjwatson** [comment]
Hi,

This is a noble sentiment but there are a few things that you should be aware of regarding SSC.  The most notable one is that TShock doesn't support this out of the box.  The main thing to note is that two people can be logged in to TShock on both your servers using the same account in which both of the players are essentially going to 'share' the same inventory which is a minefield of concurrency problems beyond what we can control - there are a lot of things that we have to consider:

* Who becomes authoritative when there are two players logged in to the same account?
* How do you manage inventory saves?
* How do you not overwrite inventories on log out?
* Duping across servers

SSC is tied to a server by default because a login is tied to a server.

**Comment by ChetwyndKid** [comment]
I dont know maybe it could be a planned feature or something to increase how stable stuff like that is as, If people are running large servers then they are gonna need multi server.

**Comment by Enerdy** [comment]
The thing is, if you're running a large dedicated server then you'll most likely want to use MySQL over SQLite, and MySQL already supports this as long as you connect to the same database.

**Comment by ChetwyndKid** [comment]
Fair enough, Thanks i shall look into this.

**Comment by Ijwu** [comment]
@ChetwyndKid @enerdy The considerations brought up by @tylerjwatson are still possible issues, even with MySQL

**Comment by Zoryn4163** [comment]
Has there been any further development or implementation of this? I currently have 2 servers connecting to a MySQL database and I can easily log myself in twice and dupe items freely and would like to know the current state of multi-world SSC.

**Comment by WhiteXZ** [comment]
SSC is not designed for sharing between servers, and such a feature will likely not be added into TShock in its current state.
We may possibly work on multi-world SSC in Orion/TShock 5
