### ISSUE TITLE
TerrariaServer is running in the background and input is disabled.

### ISSUE THREAD

**Issue by c0m4r** [NyxStudios/TShock#1139]
Hello,

After one of the latest updates of Tshock the server console is read-only. I am no longer able to get the output from commands entered directly to the server's console. What I noticed is this "TerrariaServer is running in the background and input is disabled." notice. Now, I've tried to find a cvar that is responsible for this, but I found nothing like this. Also googling for keywords like "terraria server" and "background" is pointless, since all the articles are about running processes in background (using nohup, screen, etc.) and that is not the point. So, is there any way to enable console input again?

Best regards,
Andrew

**Comment by Ijwu** [comment]
Is it possible that you have redirected stdout or stdin elsewhere?

**Comment by c0m4r** [comment]
Nope.

**Comment by tylerjwatson** [comment]
Hi,

It isn't clear what you are trying to acheive, so I am going to assume that you're running TShock in the background, and this is by design.  Typically if it's run in the background and there is no controlling tty then there is no point in keeping a console thread waiting for input it will never receive.  Being terraria is a poorly performing product as it is, this was an intentional choice to gain some performance, and to be a well-behaved unix daemon.

Using a console interface only makes sense when it's running in a console. Things like `nohup` will destroy a controlling terminal and thus TShock won't run a console input.

If you are running in a terminal (without redirecting stdin) and you still get that background message then we have a problem.  Otherwise, if it's genuinely running in the background then that is by design, and you may want to consider using REST to interact with TShock instead of trying to use terminal chatting.

Cheers

**Comment by c0m4r** [comment]
And this is such a discussion about "running in the background" that I wanted to avoid, because it does not apply to the subject. "Running in the background" is just misleading here. If I would redirect the stdin/stdout of the process or run it in other ways (like screen, nohup etc.) then it really would be a problem on my side and I know it. But I'm actualy running the server in a console directly, not in the background, and until one of the latest versions of Tshock I was able to get the output from commands like "help" etc. Now the server's console is read-only.

> "If you are running in a terminal (without redirecting stdin) and you still get that background message then we have a problem."

That's exactly what my problem is

**Comment by WhiteXZ** [comment]
What arguments are you using to start the program? (mono TerrariaServer.exe blah blah ...)

**Comment by tylerjwatson** [comment]
> And this is such a discussion about "running in the background" that I wanted to avoid

Until now, you have never even hinted _any_ details about how you were trying to run the program. something along the lines of *"TShock thinks it's running in the background, when in fact I am running it in a terminal"* with details of what you did to run into the issue would have sufficed, and we would have gotten a lot more context about your problem without us assuming the rest.  

The subject of this discussion is **TerrariaServer is running in the background and input is disabled**, so this semantical discussion _is_ relevant.

We aren't mindreaders and we rely on coherent reports to fix problems, and I will ask you to please remove your attitude from this discussion going forward.

Regardless of whether you think this discussion about TShock's behavior is relevant to the subject or not, the fact remains that this behavior _is_ by design:  If mono indeed detects that `stdin` comes from anywhere that isn't the controlling terminal then it _will_ run in the background and not accept input.  That is by design.

For this to be actually an issue, we need something we can reproduce.  Moving forward you need to help us reproduce your problem: What environment are you running?  How are you trying to run the process?  Mono version?  architecture?  Give us something to try and help you.

Cheers.

**Comment by c0m4r** [comment]
I've tried a few start lines:

>TerrariaServer.exe
>TerrariaServer.exe -ip X.X.X.X -port XXXX -maxplayers 10 -world "path/to/world"

etc.

"TerrariaServer is running in the background and input is disabled" is a quote from Tshock server's console:

![tshock_console](https://cloud.githubusercontent.com/assets/6292788/11558902/87c308a8-99b5-11e5-80d4-ae5a5ac4499c.png)

>If mono indeed detects that stdin comes from anywhere that isn't the controlling terminal then it will run in the background and not accept input. That is by design.

So it must be a bug in the current version of Tshock, because in my case stdin isn't redirected.

**Comment by tylerjwatson** [comment]
It looks like you're using Ubuntu.

Ubuntu has a binfmt registration that runs win32 PEs under wine if you shell them directly, which could be why the run time is incorrectly determining the console redirection.

You didn’t indicate that you are running the server with mono. As it's a .NET process, you need to install mono from the Xamarin PPAs and run the server with `mono TerrariaServer.exe`.

TShock runs on countless other Linux environments under mono just fine.

Cheers.

**Comment by c0m4r** [comment]
I am using Ubuntu on my desktop. The server is set up remotely on Debian.
Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)
