### ISSUE TITLE
Is there new version REST api?

### ISSUE THREAD

**Issue by darkautism** [NyxStudios/TShock#1144]
i watch this message on my server
"deprecated": "This endpoint is depracted and will be removed in the future."

and i seen the orion project, but the v3 api not work now.
and i can not access v2 too.

**Comment by WhiteXZ** [comment]
Which endpoint?

**Comment by darkautism** [comment]
http://127.0.0.1:7878/v3/token/generate

I found there has some v2 rest api in the tshock code

is there any v2 and v3 document?

**Comment by WhiteXZ** [comment]
The reason /token/generate says it's deprecated is due to the fact that there was a planned re-make of the REST API that never happened. The warning can be safely ignored, as the endpoint should still function correctly.

We have documentation for the /v2/ endpoints [here](https://tshock.atlassian.net/wiki/display/TSHOCKPLUGINS/REST+API+Endpoints).

Orion should have an overhauled REST API. There is no guarantee that it will have any similarity with the current API.

**Comment by darkautism** [comment]
https://github.com/NyxStudios/TShock/blob/v4.3.11/TShockAPI/Rest/RestManager.cs

I found some v3 REST api is implement

and it's work.
