### ISSUE TITLE
[SSC] Favourited Items Being Forgotten

### ISSUE THREAD

**Issue by Zoryn4163** [NyxStudios/TShock#1148]
Whenever someone favourites an item, disconnects, and rejoins, the item will no longer be favourited.
If someone *really* wants a video of this I can provide but it's very easy to reproduce. This occurs using a MySQL Database, but I would assume it would also occur using SqLite.

**Comment by Enerdy** [comment]
Unfortunately, this is something we cannot fix by ourselves at this point. SSC is set to override everything including favorites, but the favorited slots in a player's inventory are never sent to us, so we cannot store it nor stop it from being overriden.

**Comment by YoYoK3nny** [comment]
Could this be re-looked into? I had a quick look at the decompiled source for the vanilla TerrariaServer and it does reference favorited items.

From what I could see I believe the property is stored on the inventory slots themselves, rather than as a separate set of favorites slots.

If this is correct then the SSC feature would need to reference the property to save/load which slots are favorited. (Much like it is specifically referencing `.stack` and `.prefixid`)

If the Terraria client is indeed not actually sending that property, then feel free to ignore this.

For reference, the property is:  `.favorited`

**Comment by QuiCM** [comment]
The property is never sent to the server unfortunately :(

**Comment by YoYoK3nny** [comment]
Well, heres hoping that this bug is fixed in the Journey's End update. Otherwise there's a whole bunch of useless code in Re-Logics own server source.
