### ISSUE TITLE
Add /ban info

### ISSUE THREAD

**Issue by Strinkor** [NyxStudios/TShock#1180]
Add /ban info for displaying detailed info abou ban.

- Date and time
- Banned user ip
- Banned by
- When expired

**Example usage:** /ban info <username>

**Comment by ProfessorXZ** [comment]
There are plugins that already do this (e.g ZAdminCmds), so I do not see a point in adding it now.

**Comment by Strinkor** [comment]
Why it's can't be added to TShock? :)

**Comment by Celant** [comment]
Hey Strinkor.

This is not likely to be added, as something like this seems a bit over-complicated for TShock. TShock handles a ban list, and nothing more. To do this, more information about the bans would need to be recorded which is a bad idea currently. The second issue is that at the moment not a lot of new features and functionality are being added to TShock, because the devs are working on TShock 5.

**Comment by Strinkor** [comment]
Maybe, yes, if devs working on TShock 5, then , i think, we can wait :)
