### ISSUE TITLE
Chat Message String Length

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1192]
It looks like 1.3.1 came with a new packet SmartTextMessage  packet 107 and the new tShock uses this for it's SendMessage() functions.

I'd like to request it be changed back to ChatText packet 25, which allows for much longer strings before the client forces a line break...

Example Screenshots.
http://imgur.com/a/gWZeU

Please change this back :x

I don't understand whats "smart" about SmartTextMessage packet 107...

**Comment by Enerdy** [comment]
The char limit per line remains the same. All this does is force words that are too long to split, so that you don't get incredibly long chat lines that were never meant to be. This won't really affect you unless you spam a ton of chat tags (such as what you did in yout screenshot) in a row /without/ having spaces between them. If you add spacing it won't hyphenize the tags (by the way, the fact that chat tags count for the line limit and/or can be broken by hyphenization is currently a bug and y0r said he'd look into it.

Considering people talk with words and not 10 emotes in a row, I don't see how will this affect them, other than making it easier to read messages in smaller screens.

**Comment by tysonstrange** [comment]
It's definitely shorter. Test it yourself or look at the first screenshot again... 

Those numbers have spaces between them. It's a good 20 characters shorter at least using packet 107

**Comment by tysonstrange** [comment]
The 3rd line where it starts back at 1 is packet 25,

New Packet 107 me talking is what the shock uses for default  chat and is clearly shorter.

**Comment by cracker64** [comment]
The 'new' chat method forces a line pixel limit of 460 of the raw characters.
The old chat is limited at 80 characters, which is can easily go over 660 pixels per line.

So the new chat is significantly shorter with the same regular text being drawn.

**Comment by tysonstrange** [comment]
I don't think it's based on  pixels since if you link item Or colour tags it becomes shorter again. I just did items so you can see the parsing line break bug  too. 

Either way, can you please change it back?

**Comment by Enerdy** [comment]
@tysonstrange He did mention "raw characters", so that means the item tag's characters before they're converted. Line pixel limit of the final result is what they should implement in order to make such tags more usable without reducing the line's effective length.

**Comment by Enerdy** [comment]
I hereby present you my solutions:
A) Make a config option, "UseNewChatPacket" or something, to let users choose whether or not they want this new word-wrapping feature of not.
B) Keep packet 107 as the new standard
C) Revert the change and refrain from using packet 107 until it is further improved by Re-Logic so that it doesn't actually shorten chat lines
cc @NyxStudios/tshock

**Comment by tysonstrange** [comment]
I'd consider using it if Relogic made it the same pixel length (or even better, have it by dynamic, but i dont expect them to be able to figure that out...)

But if you think players don't use colour tags or arnt going to link several items ina row you've never played a multiplayer server before or are just trying to kid yourself...

Either way, I'd appricate if it was atleast an option, because i'd rather have longer chat lines, since this new one not only messes up player chat but all the tShock pagination tools are out of whack too.

I'll even compile my own build if you dont, but I really dont want to have to worry about doing that every time theres an update.

**Comment by cracker64** [comment]
I think it would be possible to have TShock use the pixel-length method and send the resulting lines to clients, this would allow to fix the item parsing bug regardless of Re-Logic, and configurable line lengths for servers.

**Comment by tysonstrange** [comment]
>It would have to send the old 25 packet until Re-Logic fixes it in the client code, and nothing could still go past client line length restrictions

Yeah, wihich is about the 80~ or so letters worth of pixels in lengt anyway.

I'm using a custom compile atm using packet 25 again, coz chat looks shit with 107
