### ISSUE TITLE
Unicorn Mount Dismounting Teleports you to previous location

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1197]
This is a strange bug, but I think it has to do with TShock and how it handles your movement via Mount and back to walking. If you are on the ground while using the Unicorn Mount, simply go full speed and then Dismount with "R". You will get the Rod of Discord Teleport noise on you and animation.

Perhaps its something to do with a permission or maybe just threshold? Can't seem to find a fix, but Doesn't happen on superadmins account last I checked. Will confirm later.

**Comment by Marcus101RR** [comment]
![image](https://cloud.githubusercontent.com/assets/8344293/15733101/a745b2b4-2850-11e6-93de-4d98ff490377.png)

Screenshot shows that I dismounted a Unicorn Mount, and got Teleported back a large distance after dismounting using a non Admin account.

**Comment by cracker64** [comment]
Alright well I did find the cause of this issue.
TShock is doing an improper noclip check while riding a Unicorn (possibly other mounts with different player sizes).
It appears to be checking -down- two tiles too far, instead of the intended -up- for the two extra Unicorn height.

In your screenshot the thick floor is actually causing the failed noclip check. Trying this on a 1 or 2 thick floor will have no issues due to how the check works.

**Comment by g1zstar** [comment]
[Thick floor.](https://gfycat.com/FlashyPersonalAndeancat)

[Thin floor.](https://gfycat.com/BadFlawlessGecko)
