### ISSUE TITLE
Buff Bans

### ISSUE THREAD

**Issue by IamUSER** [NyxStudios/TShock#1212]
More of a feature request than an issue. Is it possible to introduce the ability to ban the application of certain buffs. For example the DCU is a buff and an Item and Shadow Dodge is generally considered op. Thanks!

**Comment by Patrikkk** [comment]
As far as I'm concerned, there are 3 kinds off buffs.
1. Time buffs, what ends within an x amount of time. (gills, etc)
2. Constant buff, which gets turned on once, (pet buffs, etc)
3. Constant buffs what are kept toggled on at every tick (Campfire buff)

Thing is at case 3. you cannot disable at all because they are being turned on in the client literally every tick. Like the campfire buff, for example.   I assume it's the same with DCU buff?
The other two case, you can turn the buff off. Altho second case would require SSC.
Correct me if I'm wrong :)

**Comment by Strinkor** [comment]
@Patrikkk I think, players won't happy, if buffs got from armor sets, like Solar Set, will disabled, but this idea have some point.

**Comment by gyrodrill** [comment]
https://github.com/gyrodrill/BanBuff

**Comment by Kojirremer** [comment]
Requesting this to be reopened since the author of BanBuff is MIA and the plugin has dissapeared from Github.
