### ISSUE TITLE
Removal request for item-hold bans.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1213]
No seriously @WhiteXZ , This feature causes people to get stuck who are holding banned items, neither does it change the fact that people can still place banned structures if the tile itself is not banned, I suggest only applying these kind of item bans to usable items instead of every item as people get stuck and have to either die or get kicked as they cannot press ESC to leave and causes them to lose the item they are holding.

**Comment by WhiteXZ** [comment]
Don't ban the item?

**Comment by Patrikkk** [comment]
On a different note, could we just still use frozen buff instead of stoned? :) This is a thing since 1.3, when stoned became a thing.
As mentioned, they can't even change the item or do anything, just restart their client/rejoin.

**Comment by Enerdy** [comment]
The thing is, it's impossible to gain immunity to the stoned debuff by any means other than hacking, AFAIK. It is, however, possible to gain immunity to the frozen debuff through an item. If someone is not affected by `stoned`, you can safely assume they're not running an original client, which is why it is a better choice.

**Comment by tlworks** [comment]
@WhiteXZ Worthless answer, don't you see that banning the item is required. This counts for every item in the whole game.
