### ISSUE TITLE
Fix quick stack ignoring chest protection

### ISSUE THREAD

**Issue by MarioE** [NyxStudios/TShock#1250]
We have chest protection in regions, but this is inconsistent and does not apply to quick stack.

**Comment by Patrikkk** [comment]
It is possible to handle packet 85 (`Force Item Into Nearest Chest`) so player cannot stack item to nearby chests.
But currently this makes the item in the slot, what was about to get stacked into the chest to be frozen, the player cannot move the item or replace it in the slot.
This is happening because `Player.inventoryChestStack` bool array doesn't get set back to false. (It gets set to true when the player attempts to stack item into nearby chest)

```
if (!Main.player[Main.myPlayer].inventoryChestStack[num5])
{
	if (Main.mouseLeftRelease && Main.mouseLeft)
	{
		ItemSlot.LeftClick(Main.player[Main.myPlayer].inventory, 0, num5);
```
So unless we figure a way to set `inventoryChestStack[id]` back to false, handling packet 85 is not possible.

**Comment by ProfessorXZ** [comment]
I've come up with 1 solution so far, here's the code: 
```
private static bool HandleForceItemIntoNearestChest(GetDataHandlerArgs args)
{
	var id = args.Data.ReadByte();

	try
	{
		if (TShock.CheckTilePermission(args.Player, Main.chest[id].x, Main.chest[id].y) && TShock.Config.RegionProtectChests)
		{
			return true;
		}

		if (TShock.CheckRangePermission(args.Player, Main.chest[id].x, Main.chest[id].y))
		{
			return true;
		}
	}
	finally
	{
		Array.Clear(args.TPlayer.inventoryChestStack, 0, args.TPlayer.inventoryChestStack.Length);
		for (int i = 0; i < 58; i++)
		{
			NetMessage.SendData(5, -1, -1, "", args.TPlayer.whoAmI, i);
		}
	}

	return false;
}
```

Now this is not the final result, but it works. In order to prevent the slots freezing we have to reset the array and update the player's inventory. One does not work without the other. Would be nice to hear others' opinion on this, since I'd like to know if anyone has a "prettier" way of implementing this.

**Comment by WhiteXZ** [comment]
Discussion in slack has resulted in a new hook added to TSAPI which should allow us to block quick stacking in TShock
