### ISSUE TITLE
ShowFiletoUser MOTD color parsing failure

### ISSUE THREAD

**Issue by DogooFalchion** [NyxStudios/TShock#1314]
While the spec for Terraria is one color per line, the design of the MOTD color parsing fails if multiple colors are present in one line.  The reason is because as it removes the first color string %###,###,###%, it does not keep track of that.  The string is now shorter than it was and the indices in the next match no longer correspond with the correct characters in the string.  

A solution could be if multiple matches are made, the MOTD should show some intelligible error to the player and not show the MOTD as well as a console message for the server owner explaining the one color per line terraria limit.

Another solution is to properly handle multiple colors by only using the first or last color and to not using String.Remove().

See https://tshock.co/xf/index.php?threads/something-went-wrong.4851/ for an example.

**Comment by Simon311** [comment]
Doesn't the new chat packet support multiple colors and item display in the string?
Should probably just remove the colors altogether and tell people to format it the Terraria-way

**Comment by ProfessorXZ** [comment]
TShock parses files on it's own. It will iterate over the file and look for the rgb format, thus it's not the packet's fault really.

**Comment by Simon311** [comment]
@ProfessorXZ Did you even read what I wrote?

**Comment by ProfessorXZ** [comment]
Yes I did, and I told you it is not the packet's fault. 
>Doesn't the new chat packet support multiple colors and item display in the string?

**Comment by Simon311** [comment]
@ProfessorXZ Well then, let me reiterate.
I am fully aware of how TShock handles motd and I did not blame the packet at all.
What I said is, that there is now a packet and a whole system of tags to support colors natively in Terraria, and therefore we should not apply any new additions to our system. In fact, we should probably remove our own system for parsing colors and tell people to rely on Terraria's chat tags.
Next time, please re-read my full message for as long as it takes to understand.

**Comment by Simon311** [comment]
The current system also does not require any additions on our end. If we want to keep the backwards-compatibility - then no changes are required at all, aside from changes to our guidelines on formatting the MOTD file.
![image](https://cloud.githubusercontent.com/assets/1058851/19550575/c1da8bec-96b2-11e6-9457-f827d23b5dc6.png)

**Comment by Simon311** [comment]
The issue though is mostly about our method not correctly handling an error, this needs some work indeed.

**Comment by WhiteXZ** [comment]
For the record, the alternative to simply removing our parsing was to translate as such:
`%255,255,255%This is some text! %255,0,0%This text changes colours on the same line!`
->
`[c/ffffff:This is some text!] [c/ff0000:This text changes colours on the same line!]`

Due to having to match then remove parts of the string, then find the next match if any in the string (while taking into account any removals/additions) etc etc, removing our parsing was the easier option.

**Comment by nicatronTg** [comment]
@WhiteXZ I for one think removing my color system was mean.

**Comment by Simon311** [comment]
@nicatrongTg @WhiteXZ This is bad really. We should've given people time to transition instead of just breaking their setups with the next release.
Besides, having the base color of a string was a good thing to have, would allow some sort of nesting, which tags don't support.

**Comment by nicatronTg** [comment]
Kinda agree with @Simon311 on this one as far as backwards compatibility + upgrading goes.

**Comment by DogooFalchion** [comment]
If no one has any objections I don't mind converting the old context into something that uses this new chat format.

**Comment by nicatronTg** [comment]
Would be nice to have.

**Comment by Simon311** [comment]
The issue needs to be reopened. 
And I do mind. Admins are not dumb, they can use the Terraria format on their own. However, they can not nest colors with it, but they could with our previous setup, set the string's base color and then insert tags in it, which is VERY MUCH more usable, than having to format each part of the string with yet another tag (no matter our system or Terraria's, especially considering ours is even more confusing since our tags are not closable).
My vote is to keep the current system as it is. Its not like by implemeting support for specifying color mid-string it stops being a problem in previous releases.

**Comment by Simon311** [comment]
Frankly, I want WhiteXZ's commit reversed and then the exception/error fixed to not fuck anything up, that's it.
