### ISSUE TITLE
Issue with latest version of TShock

### ISSUE THREAD

**Issue by MrExzibit** [NyxStudios/TShock#1330]
Hello,

I'm having an issue with the latest version of TShock. Basically, I tried opening the server on an older version of TShock and I kept getting an error everytime I tried running TShock. I updated to the latest version and I still get the same message which says this:

![image](https://cloud.githubusercontent.com/assets/16407673/20681733/c57c79b4-b59c-11e6-8aa0-5fa37bad7a0b.png)

I deleted the folder with the old version and installed the new version into it, I don't know what to do.

Thanks in advance.

**Comment by nicatronTg** [comment]
Follow the instructions for outdated world metadata on [the ultimate help guide](https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/). While not directly addressed, I believe this to be the same problem.

If that helps, let me know and I'll add it to the guide.

**Comment by MrExzibit** [comment]
I removed the worlds from the world folder and I had 2 different files for 1 world and 1 different file for 1 world. After I put in the world that has 1 file, the error was gone. However when I opened the .exe it gave me an option to A: Create new world or B: Delete a world. With no option to play the world that I have put in.

I then put in the world that has 2 files one being a .bak and .wld | After I put these 2 in the error shown up. 

I tried putting the world in TEdit so I can update it like the guide said however, the only file that I could select was a .wld file from the world that had 2 files. After I tried opening the world that has .wld in TEdit it shown some kind of error and in TEdit it would not load up that world. Rather strange situation.

**Comment by nicatronTg** [comment]
The vanilla server can load the world that neither TEdit or TShock can open?

**Comment by tlworks** [comment]
I highly suggest you use WorldEdit and InfiniteChests plugin in the future regarding this issue, as you will be able to simply copy your world over to another with WorldEdit and the InfiniteChests plugin will take care of the chest data placed inside that world.

This is because due to some changes in the recent Terraria (Version 1.3.3.3) all worlds _most likely_ (doesn't always have to) break and you'll have to generate a new one using the latest Build.

Hope this helps.

**Comment by nicatronTg** [comment]
@tlworks this I take it this is a fairly widespread issue you've found?

**Comment by MrExzibit** [comment]
@nicatronTg With TShock it would not show any world to load. It simply gave me the option to create a new world or delete a world. In TEdit when I tried opening a world file with .wld it was forever saying "undoing tiles" i believe. Not sure if that's what it said.

**Comment by tlworks** [comment]
@nicatronTg Started occurring to me ever since 1.3.3.3, the explanation I stated above is the most _efficient_ way that kind of fixed it for me. Unless this has to do with a missing file path which then likely has to do with either the **-path** tag being used in a shortcut or the **path=** option in the config.txt file.

I mean if the World is being created correctly in the newest Build and WORKS then I suggest using the method above.

**Comment by LenyaKap** [comment]
Please! Help me!!!! I do everything!
Nothing work!

**Comment by tlworks** [comment]
@LenyaKap Why are you even here, and we don't even care.

**Comment by WhiteXZ** [comment]
@LenyaKap The above comment is from someone in no way affiliated with the TShock team. Their words and actions are their own and do not represent us or our opinions.

With that being said, your own comment asks for help without providing any details as to what is not working. Providing us with details of your issue will help us resolve the matter faster

**Comment by levi-middleton** [comment]
I'm having this same issue copying a 1.3.3 world from a remote server to a local server. I've opened the world in tEdit and saved it; this did not fix the issue. What other diagnostic steps or information would be helpful?

**Comment by MrExzibit** [comment]
[Update]

After I put in the only world that gives no error. I opened the server and when you select what world you want to host on, it did not give the option to host on the world that's in Terraria. It just gave me the option to create a new world or to delete a world. I attempted to create a new world from the .exe and upon creating the world it said that I wasn't using the same version of Terraria I believe it said.

**Comment by MrExzibit** [comment]
Here's a just under 2 minute video I made showing basically what happens.

https://www.youtube.com/watch?v=2FQzTxY654I

**Comment by WhiteXZ** [comment]
Thanks @mrexzibit, I'll check that out in a few hours when I get up. 
If you find a way to solve it (or find more problems) before then, just keep sending feedback and I'll make sure to check it all when I can :)

**Comment by MrExzibit** [comment]
@WhiteXZ No problem, if you need me to do anything I can happily attempt it and probably upload it to youtube to show what exactly happens.

**Comment by WhiteXZ** [comment]
I've checked out your video @MrExzibit and I've identified a few issues:
* The latest release on our Github releases page is currently outdated and is for 1.3.3.3. Beta builds for 1.3.4.3 can be found at https://travis.tshock.co/general-devel/
* The reason your `I_dont_KNow.wld.bak` world doesn't display in the TShock world select menu is because of the `.bak` extension on it. `.bak` simply means it's a world backup, you should be able to safely remove the `.bak` and leave it as `I_dont_KNow.wld` and it will be available again.

**Comment by MrExzibit** [comment]
Ah gotcha, thank you for the solution. Thank you for anyone who helped!
