### ISSUE TITLE
/butcher can't kill tenant NPCs

### ISSUE THREAD

**Issue by Kojirremer** [NyxStudios/TShock#1332]
I've seen this bug recently on the latest stable version, but confirmed it's still happening on the unstable version being stress-tested right now.
When you use /butcher on enemy and critter NPCs, they die as expected. However, on tenant NPCs they take  almost lethal damage, but still manage to survive in critical condition. Even when they are critically injured right after a /butcher, repeating the command will still not be able to kill them.

**Comment by tlworks** [comment]
This might or might not be relevant to this issue, but might just throw it in there. After you use /butcher, can you try hitting that monster and see if it disappears OR could you check and see if it still causes damage to other players? Since on my Server I do come across an issue where monsters have died on other people their clients, but not my own even though I butcher.

**Comment by Kojirremer** [comment]
I've seen that too, but seems to be unrelated. When you butcher and phantom mobs are left client-sided, trying to butcher again will not register those as hits. However, trying to butcher the near-death tenants will register as butcher hits (Server has butchered <Number> npcs.).

**Comment by Marcus101RR** [comment]
Seems to be fixed in https://travis.tshock.co/general-devel/1438/

**Comment by ProfessorXZ** [comment]
Closing this as the latest report says it has been fixed. Feel free to reopen the issue if it happens again.
