### ISSUE TITLE
Tshock Server start up error.

### ISSUE THREAD

**Issue by iWerm** [NyxStudios/TShock#1333]
Whenever I open up the TshockServer application, this shows up. (I completely deleted TShock and downloaded the newest stable build and this continues to happen. Any help would be greatly appreciated
![tshockerror](https://cloud.githubusercontent.com/assets/24379430/20872707/61a03146-ba66-11e6-9025-a08d5115af40.png)

**Comment by Kojirremer** [comment]
This has been addressed quite a bit already the last few days. It's because you have worlds that have version issues with your current TShock.

Do you have any world you have recently opened in 1.3.4.x in your "Worlds" folder? If that's the case, this will happen because TShock for Terraria 1.3.3.3 tries to read data from worlds from a newer Terraria version and, once hitting the unknown 1.3.4.x data, this crash occurs.

If you know which world has been converted to 1.3.4.x format, you will have to isolate it/them from the Worlds folder so TShock doesn't try reading the data. If you don't know which one is it, you will have to remove all maps and try adding them back one by one until you find out which one causes the conflict crash.

**Comment by ProfessorXZ** [comment]
This has been covered in the ultimate guide too. https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/. @iWerm is there any reason why you left this issue open?

**Comment by iWerm** [comment]
@ProfessorXZ Forgot to :P my bad
