### ISSUE TITLE
/logout Command Permissions Not Granted by Default

### ISSUE THREAD

**Issue by aarongoulet** [NyxStudios/TShock#1371]
Users are unable to use the /logout command by default, which could be problematic in some cases (such as superadmins who /auth after having already registered and logged in using a different account, which renders them unable to switch to newly created superadmin account).

**Comment by ProfessorXZ** [comment]
I don't see this as an issue that needs fixing honestly. There probably is a solid explanation why this wasn't added. Personally groups shouldn't have any permissions to begin with. Another thing to note is that if you have access to /auth you most certainly have access to the console, which lets you add the permission to the desired group to make them log out.

**Comment by kinvaris** [comment]
@ProfessorXZ it is an issue that needs fixing but maybe not right now. As @aarongoulet mentioned a user should be able to switch between accounts. In my opinion, the `default` user group should always have some rights e.g. logout, ...

**Comment by nicatronTg** [comment]
I believe this was intentionally not added to the default permission set, because it allows servers who have login before join to ensure that all players connected are logged in.

I'm opposed to changing the default.

**Comment by DogooFalchion** [comment]
1. LoginBeforeJoin does not enforce RegisterBeforeJoin, therefore a new player will still join as a guest, and /register.
2. If a server owner does not want players on the server to be able to logout, then they should change the default group for newly registered players or remove it from default.  (iirc TShock will not force overwrite existing groups...)
3. The obvious to me as an end user is that if I have /login then I should have /logout.  Before this wasn't an issue because /logout wasnt a command.  Now that it is, it kinda makes sense that the two would be tied together somewhat.

2cents is that it takes 20 seconds to make the change.  I suggest the team either close this ticket or allow the PR making the change.  Letting the issue idle for 2 weeks is lol.

**Comment by OnsenManju** [comment]
I feel it might not a technical matter or reasonableness but a something like design concept of TShock though.
> The obvious to me as an end user is that if I have /login then I should have /logout. Before this wasn't an issue because /logout wasnt a command. Now that it is, it kinda makes sense that the two would be tied together somewhat.

If TShock will let users to able to logout by default in future, I also hope current 2 permissions (_tshock.account.login_ and _tshock.account.logout_) will be unified into one.

**Comment by nicatronTg** [comment]
> The obvious to me as an end user is that if I have /login then I should have /logout. Before this wasn't an issue because /logout wasnt a command. Now that it is, it kinda makes sense that the two would be tied together somewhat.

That's logical. I agree with this sound reasoning.

> If TShock will let users to able to logout by default in future, I also hope current 2 permissions (tshock.account.login and tshock.account.logout) will be unified into one.

That would make it impossible to replicate the current functionality. I'm opposed to this change.

**Comment by aarongoulet** [comment]
Pull request submitted.  Please see: https://github.com/NyxStudios/TShock/pull/1417

**Comment by aarongoulet** [comment]
Pull request approved by @hakusaro.  Ready to be merged!

**Comment by hakusaro** [comment]
Pull requests to TShock require approval of two collaborators, not one.

**Comment by aarongoulet** [comment]
Oh, my bad. 👍
