### ISSUE TITLE
Should issues with the Terraria source code be reported here? 

### ISSUE THREAD

**Issue by Plazmaz** [NyxStudios/TShock#1389]
I'm curious as to what your policy on issues in Terraria's source code is. If I wanted to fix a bug in the server source, would you accept the PR, or do you want it to remain true to vanilla, bugs and all?

**Comment by ProfessorXZ** [comment]
The server is no longer decompiled and you can't easily push bug fix PRs.

**Comment by Plazmaz** [comment]
Ah, so does TShock function using binary patches or something?

**Comment by Enerdy** [comment]
I don't see the point in reporting an issue with vanilla to us instead of the Terraria development team. If an issue is confirmed, they tend to try and fix it on their next release, right?

You might not want to wait until the next Terraria release, which can take longer than a TShock one, but in one way you'd be doing duplicate work. We've disregarded glitches that can be reproduced in vanilla as well in the past for this reason, specially when people came complaining to us about "our glitch" when we were not the ones at fault.

My personal answer is no, we should not be fixing issues with Terraria itself. I'd like to hear the thoughts of other @NyxStudios/tshock members on this matter, though.

**Comment by Plazmaz** [comment]
Terraria's development team doesn't seem to respond to smaller/minor bugs. It'd be nice to be able to fix some of the older issues.

**Comment by ProfessorXZ** [comment]
:+1: for Enerdy. This is in fact a server plugin, so it's not this team's job to fix the game itself.

**Comment by nicatronTg** [comment]
You should definitely report your issues to [Terraria directly](https://forums.terraria.org/index.php?forums/pc-bug-reports.113/) unless you find security problems with our code or client/server delegation issues that aren't fixed in Vanilla (e.g., client has control where server should and _can_ have control) that we can fix. Otherwise, it's quite pointless to tell us because we now use the Open Terraria API to handle changes. This makes fixing issues in the decompiled code an impossible workflow now.

**Comment by Plazmaz** [comment]
Alright, thanks for the clarification.

**Comment by nicatronTg** [comment]
_We are aware that many bugs don't get fixed in Terraria. While the team gets them and works on them, unfortunately, there are usually a far greater number of bugs in the software than can be fixed in a release window._
