### ISSUE TITLE
tShock mono docker

### ISSUE THREAD

**Issue by TimVNL** [NyxStudios/TShock#1393]
Hello,

I don't know where to place this but I am working on a minimal docker debian mono tShock container and i am getting the following error:

`100.0% - Generating Structures. - 0.0%
Saving world. Momentary lag might result from this.
Saving world data: 30%
100.0% - Generating Structures. - 0.0%
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
  at Terraria.IO.WorldFile.LoadWorld_Version2 (System.IO.BinaryReader reader) [0x0000d] in <415a07e3eda047659e54b938a1a3f232>:0 
  at Terraria.IO.WorldFile.loadWorldDirect (System.Boolean loadFromCloud) [0x000e7] in <415a07e3eda047659e54b938a1a3f232>:0 
System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
  at Terraria.IO.WorldFile.LoadWorld_Version2 (System.IO.BinaryReader reader) [0x0000d] in <415a07e3eda047659e54b938a1a3f232>:0 
  at Terraria.IO.WorldFile.loadWorldDirect (System.Boolean loadFromCloud) [0x000e7] in <415a07e3eda047659e54b938a1a3f232>:0 
Load failed!  No backup found.`

I am installing these packages: 
`install_packages net-tools psmisc apt-utils libgdiplus libjpeg8 libmono-corlib4.0-cil libmono-data-tds4.0-cil libmono-sqlite4.0-cil \
   libmono-system-core4.0-cil  libmono-system-data-linq4.0-cil libmono-system-drawing4.0-cil libmono-system-messaging4.0-cil \
   libmono-system-net4.0-cil libmono-system-runtime-serialization-formatters-soap4.0-cil libmono-system-runtime-serialization4.0-cil \
   libmono-system-runtime4.0-cil libmono-system-servicemodel4.0a-cil libmono-system-web-services4.0-cil libmono-system-web4.0-cil \
   libmono-system-xml-linq4.0-cil libmono-system-xml-serialization4.0-cil libmono-system-xml4.0-cil libmysql6.4-cil mono-runtime \
   mono-runtime-sgen unzip`

I am using https://hub.docker.com/r/bitnami/minideb/ wheezy as base image  

I would appreciate any help

**Comment by nicatronTg** [comment]
You probably shouldn't run TShock in Docker, because you'll lose the world file and the database if anything goes wrong. You lose all of the advantages of Docker by doing that. There are [articles](https://myopsblog.wordpress.com/2017/02/06/why-databases-is-not-for-containers/) on [why databases in Docker are a bad idea](https://www.percona.com/blog/2016/11/16/is-docker-for-your-database/) and those largely apply to TShock. TShock isn't a microservice -- it's a full blown state driven server that's doing a lot of work to run a very RAM intensive (2gb+) game with some slight server addons.

That being said, you may have luck looking at several of the following Docker/TShock setups:

* https://github.com/kalhartt/docker-tshock
* https://hub.docker.com/r/ryshe/terraria/
* https://github.com/izissise/docker-terraria

Finally, [our official instructions say](https://tshock.readme.io/docs) to just install `mono-complete` and not individual packages. We make no guarantees about maintaining compatibility with more selective installations (e.g., if we add a feature that uses a new library that's present in `mono-complete` but isn't in your specific install script).

**Comment by nicatronTg** [comment]
_To be clear, you can totally do it right, but it's very easy to do wrong and have those data loss issues._
