### ISSUE TITLE
Player could not join server after some time

### ISSUE THREAD

**Issue by mistzzt** [NyxStudios/TShock#1404]
After running for about 3 hours, my server met some problem which happened several times in the past
.
All players on server first **lost connection**, and when they tried to connect the server, their Terraria game always displayed "**Found server**" and didnt join the server.
The server console showed that  "**xxx.xxx.xxx.xxx(IP) is connecting to the server**", but no one could joined.
![problem](https://cloud.githubusercontent.com/assets/12794966/23577472/c21e39ca-00fa-11e7-801e-30089fb7b6e8.png)
Meanwhile, the windows system became very lag; i cannot even connect to my server using RDP.

However, there is no error or exception message in logs.

**I dont know whether it is a TShock-related bug or a Terraria server-related one, but this did happen several time.**

I deleted many chat message and unrelated things in logs.[log.txt](https://github.com/NyxStudios/TShock/files/818496/log.txt)

**Comment by tlworks** [comment]
This means your Server has Deadlocked, now there could be a million causes to this happening though in all honesty I had this issue a lot when I ran through Mono on Linux hence why I ported over to Windows. But this was about 2 and a half years ago so I doubt that's the issue now since you are *NOT* running on Mono/Linux.

My Servers sometime do Deadlock as well, but the cause is always unknown and it rarely happens anymore. This could most likely be a plugin causing issues. It is to be advised to run either a debug version of TShock or get a program profiler to check and see where it hangs.

**Comment by mistzzt** [comment]
I removed UpdateManager and StatTracker, as well as logging of a plugin.

Now the server has run for a day without being deadlocked, which is better comparing with yesterday when the server deadlocked twice.

I'll reopen this issue if the same problem happen again.
