### ISSUE TITLE
Command /login & /register send password into console

### ISSUE THREAD

**Issue by Marcus101RR** [NyxStudios/TShock#1416]
![image](https://cloud.githubusercontent.com/assets/8344293/24336599/2d9f29d6-1260-11e7-9964-6594db47b4d2.png)

TShock: 4.3.23 for Terraria 1.3.4.4 (APIv2.0, OTAPI v2.0.0.16)

Not sure why this never was an issue, making it an issue now. As much as anyone wants to know any server owner can see your password entry for your account and should those people use their real private passwords, you are in bad luck.

This should be fixed so that /login and /register and any auth commands do not pass additional info after it.

**Comment by gyrodrill** [comment]
It may cause by some plugins you have installed, because the original version will not display it in console.
https://github.com/NyxStudios/TShock/blob/general-devel/TShockAPI/Commands.cs
In line 229 and 247 (DoLog = false;), it means that executing these command will not be logged.
Maybe some pugins edit the command to display it?

**Comment by Marcus101RR** [comment]
Strange, ill have to look into that, thanks.
