### ISSUE TITLE
World name in greeting text from Angler is blank

### ISSUE THREAD

**Issue by twobites** [NyxStudios/TShock#1443]
I generated a new world (Large/Expert/Corrupt) using the latest build. In text greetings from the Angler, once obtained, that are intended to contain the world name, the name is shown as blank.

![angler-bug](https://cloud.githubusercontent.com/assets/967644/25831417/f1ddd3c2-3431-11e7-8cd5-89837317e61e.png)

**Comment by mooninitevii** [comment]
I may be wrong but I believe there is a double space here indicating another bugged string.

![screenshot 2017-05-08 22 00 02](https://cloud.githubusercontent.com/assets/24752884/25832626/c869efbe-3439-11e7-87fb-8f463761066b.png)

**Comment by Ijwu** [comment]
Is this confirmed to be a TShock specific issue? Does this occur on vanilla? Does this occur without TShock but with OTAPI? Does this occur without any other plugins? 

Sorry about the basic questions, they help us narrow down an idea of what might cause this.

**Comment by twobites** [comment]
Just tried a vanilla server and you are correct in your guess. The world name shows up blank there too. Looks like it is not TShock specific but an issue with 1.3.5.3, at least on MacOS, launched via mono.

**Comment by Ijwu** [comment]
I hate to say it, but, if we've confirmed this to be an issue with vanilla Terraria then it should be reported to Re-Logic. It's best that we don't attempt to fix bugs in vanilla unless they're large hindrances so that we can minimize the amount of repeated work.

Closing for now, feel free to comment or re-open with justification if you believe this should be fixed with TShock.
