### ISSUE TITLE
autocreate command line argument don't work

### ISSUE THREAD

**Issue by Tagnard** [NyxStudios/TShock#857]
I have tried to start the server with both the command line arg and a configuration file but it still wants me to create the world.

     version: TShock.4.2.4.0128

Tested these commands but i am still required to manually create the world.

    mono TerrariaServer.exe -autocreate 3 -worldname Test
    mono TerrariaServer.exe -config serverconfig.txt

    # serverconfig.txt
    maxplayers=8
    port=7777
    password=sup3rs3cretPa55w0rd
    #motd=Please don’t cut the purple trees!
    worldpath=/world
    autocreate=3
    worldname="Docker World"
    #banlist=banlist.txt
    secure=1
    lang=1
    #upnp=1
    #npcstream=60
    priority=1

**Comment by nicatronTg** [comment]
For the autocreate flag to work, you must specify, all in one command, all parameters the server will ask during startup in order to bypass the startup flow. The documentation for startup command line parameters is [on the wiki](https://tshock.atlassian.net/wiki/display/TSHOCKPLUGINS/Command+Line+Parameters).

This is the command I ran:

```
➜  Downloads  mono TerrariaServer.exe -autocreate 3 -world test.wld -port 7777 -p 127.0.0.1 -maxplayers 16
```

This is what happens after it generates a world and starts:

![](http://puu.sh/fB6J5/857c1af8ca.png)
