### ISSUE TITLE
Not very important

### ISSUE THREAD

**Issue by sabrewolf** [NyxStudios/TShock#990]
Hi. Was wondering whether it is possible to have the link for TShock latest updates to be something as such:
https://github.com/NyxStudios/TShock/releases/download/latest/latest.zip
This will allow us to automatically update the files on our systems.

Wasn't sure where else to post this. Feel free to close and deny.

- Sabrewolf

**Comment by nicatronTg** [comment]
You should really kinda read the changelog when you download an update. What if it breaks the server? What if it wipes your world?

**Comment by sabrewolf** [comment]
This would be a client's problem. We don't allow clients to upload their own DLLs due to security issues so this would be in the "Are you sure you want to install this update" button and will make them prone to the latest version and its effects. It will probably have a link to /latest and allow them to read what is involved in the latest update. It's more to save us from coming here daily to retrieve the latest link and upload our script to install the latest update.

**Comment by Ijwu** [comment]
Here you go, friend: https://api.github.com/repos/NyxStudios/TShock/releases/latest

Relevant documentation: https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository
and
https://developer.github.com/v3/

**Comment by sabrewolf** [comment]
TCAdmin2 doesn't really allow the updates link to be changed. If i could, i would have made a script to do this already but it is just one single set link for the updates.

**Comment by pedzed** [comment]
@sabrewolf This issue is fixed now, right? If yes, please close this issue.

May I also recommend changing the title to something more clear? Something like "Link to TShock version".

**Comment by sabrewolf** [comment]
Hey. This was never resolved; sorry for the late reply. I am still awaiting for a direct link to the latest build - not a script to get one.

Cheers!

**Comment by pedzed** [comment]
@sabrewolf In what format? A ZIP file?

https://github.com/NyxStudios/TShock/archive/general-devel.zip

**Comment by nicatronTg** [comment]
That's the source code @pedzed.

**Comment by pedzed** [comment]
@nicatronTg Oh, right. Never mind.

**Comment by nicatronTg** [comment]
@sabrewolf anything outside of what Github offers would be putting more strain on us than necessary. I personally find the arrogance in the statement "This would be a client's problem" completely disheartening, coming from a former client of shared server hosting providers. While we work in depth to accommodate game service providers, such as Multiplay, Xenon, and other dedicated hosting solutions that have software needs, we have never extended our services to cater to server hosts.

Building infrastructure, such as a system for automatically providing the latest download link, actually requires a lot of integration with the Github API for us, something that nobody is really jumping up to do. Because we're working a considerable amount in getting the new version of the server API working on 1.3.0.5, and we're continually quashing software bugs aiming at a fully stable product for release, we do not foresee this issue being handled now, if ever. Typically, we experience a significant surge of updates following an update, as we patch bugs and release fixes to maintain parity with Terraria's vanilla server, and move from there forward. However, once stability is achieved, the update window becomes far, far longer, and manual checking of updates is feasible.

While we understand that margins may not be wide enough to afford hiring a developer capable of using a REST API from one of the world's largest programming services to provide a "latest update" download system for you, understand that the margins on free software are zero.

> THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
